### ISSUE TITLE
Bug with Notification stats graph

### ISSUE THREAD

**Issue by chebotar** [mozilla/wp-web-push#178] opened 2016-02-24 13:47 UTC
It's look like this on my dashboard:
![2016-02-24 16 45 16](https://cloud.githubusercontent.com/assets/3273516/13287085/2cbb6f34-db16-11e5-96cd-69c7b93caeff.png)

**Comment by marco-c** [comment] 2016-02-24 14:37
This should be fixed in the latest version, what version are you currently using?

**Comment by chebotar** [comment] 2016-02-24 15:48
0.0.8

**Comment by marco-c** [comment] 2016-02-24 15:50
Mmmh, then it isn't completely fixed. What browser are you using? And which version?

**Comment by chebotar** [comment] 2016-02-24 15:52
Chrome 48.0.2564.103 Mac OS

**Comment by marco-c** [comment] 2016-02-25 13:35
I can't reproduce this issue on Linux with my test installation.

**Comment by marco-c** [comment] 2016-02-25 13:51
Firefox:
![firefox_stats](https://cloud.githubusercontent.com/assets/1616846/13321428/d7e3ca9a-dbc6-11e5-9b2d-8bf0d8339def.png)

Chrome:
![chrome_stats](https://cloud.githubusercontent.com/assets/1616846/13321434/ddb9acd2-dbc6-11e5-8ced-d95905967950.png)

**Comment by marco-c** [comment] 2016-02-26 10:14
I've asked some of my colleagues to test it on Mac OS, but they can't reproduce the issue as well.
Any chance you could save the page and linked resources and attach it here?

**Comment by marco-c** [comment] 2016-03-07 11:15
Removing from the v1 milestone because I can't reproduce. I'll leave it open in case you have more info to add.

**Comment by marco-c** [comment] 2016-03-10 19:45
I've managed to reproduce it, it happens when the title of an article is long.

**Closed as completed** 2016-03-10 22:49 UTC
Labels: bug, analytics

**Comment by chebotar** [comment] 2016-03-14 11:42
Now it's Ok. Thanks
